### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by 687766616e** [kirnath/phpmyadmin-finder#1]
```
$ python2 find.py
 _   ___                  _   _
| | / (_)                | | | |
| |/ / _ _ __ _ __   __ _| |_| |__
| |\  \ | |  | | | | (_| | |_| | | |
\_| \_/_|_|  |_| |_|\__,_|\__|_| |_|
                       ZeroByte.ID

[!] Enter site without http:// or https:// (e.g google.com)
[+] Enter Site: test.us
[+] Processing  test.us
Traceback (most recent call last):
  File "find.py", line 77, in <module>
    main()
  File "find.py", line 63, in main
    process = requests.get('http://{}{}'.format(site,i))
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='test.us', port=443): Max retries exceeded with url: /phpMyAdmin/ (Caused by SSLError(CertificateError("hostname 'test.us' doesn't match either of '*.test.com.us', 'test.com.us'",),))
$
```

**Comment by kirnath** [comment]
Issue has been resolved

**Comment by kirnath** [comment]
`git pull https://github.com/kirnath/phpmyadmin-finder`
to update your repos
